env:
    browser: true
extends: 'eslint:recommended'
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    eqeqeq:
        - error
        - always
    camelcase:
        - error
    no-trailing-spaces:
        - error
    curly:
        - error
globals:
    angular: 0
    module: false
    describe: false
    beforeEach: false
    it: false
    expect: false
    inject: false